### ISSUE TITLE
Course3/Lab4: Usernames should always start with letters

### ISSUE THREAD

**Issue by blue-kale** [google/it-cert-automation-practice#1]
The `validations.py` file in `Course3/Lab4` includes a `validate_user` function. This function was recently modified to allow usernames to contain dots and underscores as well as letters and numbers.

The code currently validates that the first character of the username is not a number, and that was fine when only letters and numbers were allowed. Back when only letters and numbers were allowed, this meant that the username had to start with a letter. Now that we allow dots and underscores as well, we need to change the check of the first character as only letters are allowed in the first character of the username.

## Examples:
  * `validate_user("blue.kale", 3)` -> True
  * `validate_user(".blue.kale", 3)` -> Currently True, **should be False**
  * `validate_user("red_quinoa", 4)` -> True
  * `validate_user("_red_quinoa", 4)` -> Currently True, **should be False**

**Comment by lcarve** [comment]
Updated validations.py python script

**Comment by deliciafernandes** [comment]
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by abilash1907** [comment]
Close: #1

**Comment by miytk** [comment]
Updated validations.py to check first char of username

**Comment by vaibhavbshete** [comment]
The issue page times out and just shows a **Unicorn!** page in web view. It shows a picture of unicorn and says:

    This page is taking too long to load.

    Sorry about that. Please try refreshing and contact us if the problem persists.

I have commented this through github cli.

**Comment by eloiisa-gh** [comment]
The issue still doesn't load in the browser, per the previous comment.
